#pragma once

#include <cuComplex.h>

#include "sparse/DeviceWeightedLaplacian.cuh"

namespace ctqw::solver {

    /**
     * @brief Fourth-order Runge-Kutta solver for CTQW generated by a graph Laplacian.
     *
     * Integrates
     *
     *   d psi / dt = -i L(w) psi
     *
     * where the graph topology is fixed and the current edge weights are supplied
     * as a device pointer at evolution time.
     */
    class CtqwRk4Solver {
        public:
            explicit CtqwRk4Solver(
                const ctqw::sparse::DeviceWeightedLaplacian& laplacian
            );

            ~CtqwRk4Solver();

            CtqwRk4Solver(const CtqwRk4Solver&) = delete;
            CtqwRk4Solver& operator=(const CtqwRk4Solver&) = delete;

            void evolve(
                cuComplex* d_psi,
                const float* d_weights,
                float final_time,
                int steps
            );

        private:
            const ctqw::sparse::DeviceWeightedLaplacian& L;
            int n = 0;

            cuComplex* d_temp = nullptr;
            cuComplex* d_k1 = nullptr;
            cuComplex* d_k2 = nullptr;
            cuComplex* d_k3 = nullptr;
            cuComplex* d_k4 = nullptr;

            void allocate_workspace();
            void release_workspace();

            void compute_derivative(
                const float* d_weights,
                const cuComplex* d_input,
                cuComplex* d_k
            );
    };

}
